In [32]:
import torch
import numpy as np

In [33]:
int(torch.empty(1).uniform_(0., float(len([1,2,3,5,6]))).item())

2

In [34]:
torch.empty(1).uniform_(0, 10)

tensor([8.1121])

In [74]:
shift_x = np.arange(3)*3
shift_y = np.arange(4)*4


In [75]:
shift_x

array([0, 3, 6])

In [76]:
shift_y

array([ 0,  4,  8, 12])

In [77]:
shift_x, shift_y = torch.meshgrid(torch.Tensor(np.arange(3)*3), torch.Tensor(np.arange(4)*4))

In [78]:
shift_x

tensor([[0., 0., 0., 0.],
        [3., 3., 3., 3.],
        [6., 6., 6., 6.]])

In [79]:
shift_y

tensor([[ 0.,  4.,  8., 12.],
        [ 0.,  4.,  8., 12.],
        [ 0.,  4.,  8., 12.]])

In [80]:
shift_x = shift_x.reshape(-1)
shift_y = shift_y.reshape(-1)

In [81]:
shift_x

tensor([0., 0., 0., 0., 3., 3., 3., 3., 6., 6., 6., 6.])

In [82]:
shift_y

tensor([ 0.,  4.,  8., 12.,  0.,  4.,  8., 12.,  0.,  4.,  8., 12.])